#################################
#####         语言          #####
#################################
lang:
  cn: "lang_cn.yml"
  
#################################
#####         配置          #####
#################################
